config/routes.rb
Rails.application.routes.draw do
  get 'user/new'
  devise_for :users
  resources :events
  root to: 'static_pages#index'

  get 'attended', to: "events#attended", as: "attended"
  post 'attended', to: "events#attendedto", as: "attendedto"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  # On crée une sous classe creator, qui provient de User.
  has_many :event_attendees
  # Plusieurs event_attendees possible (nouvelle création de table)
  has_many :attendees, through: :event_attendees
  # A plusieurs attendees a travers les events attendees
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: 'User', foreign_key: :attendee_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :created_events, class_name: 'Event', foreign_key: :creator_id
# On créer une sous classe created_events qui appartien à Event. La clef étrangère est reliée à notre créator id de la table  event.
has_many :event_attendees, foreign_key: 'attendee_id'
has_many :attending_events, through: :event_attendees, source: :event
#A plusieurs attending_events a travers le nvo modele event. Le keyword source spécifie d'où


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  def attended
    @events = Event.all

  end

  def attendedto
    @event_id_cur = current_user.id

  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    id_cur_user = current_user.id
    @event.creator_id = id_cur_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end


  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:description, :date, :place)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/attended.html.erb
<%= render 'layouts/navbar' %>
<h1>Evenements à venir : </h1>
  <% @events.each do |event| %>
    <% if user_signed_in? && event.attendee_id == current_user.id %>
    <p>The event <%= event.description %> will take place at <%= event.date %> on <%= event.place %></p>
  <% else %>
    <p> </p>
  <% end %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= render 'layouts/navbar' %>
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>

      <th>Date</th>

      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @events.each do |event| %>
      <tr>
        <td><%= event.description %> &nbsp</td>

        <td><%= event.date %> &nbsp</td>

        <td><%= event.place %> &nbsp</td>

        <td><%= link_to 'Show', event %> &nbsp</td>
        <% @event_id_cur = event.attendee_id %>
        <td><%= link_to 'I want to go !', attendedto_path, method: :post%></td>


        <% if user_signed_in? && current_user.id == event.creator_id %>

          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% else %>
          <td></td>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Event', new_event_path %>
<% else %>
  <a href="<%= new_user_registration_path %>">Sign Up</a> or <a href="<%= new_user_session_path %>"> Login</a> to create an event
  <% end %>

app/views/events/new.html.erb
<%= render 'layouts/navbar' %>
<h1>Create a new Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Place:</strong>
  <%= @event.place %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">EvenbriteV2</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/">Home</a></li>
      <% if user_signed_in? %>
        <li><a href="events/new">Create event</a></li>
        <%else%>
      <% end %>

      <li><a href="/events">All Events</a></li>
      <li><a href="<%= attended_path %>">Events attended</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li></li>
      <% else %>
      <li><a href="<%= new_user_registration_path %>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <% end %>
        <% if user_signed_in? %>
      <li style="color: white; display: inline;"> <%= current_user.email %></li>
      <li style="color: white; display: inline;"><span  class="glyphicon glyphicon-log-in"></span> <%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
      <% else %>
      <li><a href="<%= new_user_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EvenbriteThpV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<%= render 'layouts/navbar' %>

<h2> Désolé y a pas de CSS :( </h2>
<hr></hr>
<h2> Fonctionnement du site : </h2>
<ul>
  <li> Vous devez vous inscrire (en haut à droite, sign up) pour acceder aux fonctions du site
  <li> Une fois connectés, vous aurez la possibilité de créer un évènement (la fonction s'affiche automatiquement dans la navbar)
  <li> La liste des évenements crées s'affiche dans "all event"
  <li> Si vous avez créer l'evenement, vous aurez la possibilité de l'éditer, ou le supprimer
  <li> Sinon, vous pourrez juste l'afficher en utilisant la fonction "show"
  <li> Dans l'onglet "events attended" vous êtes sensés trouver les évenements enregistrés
  <li> <b> Je n'ai pas réussi à trouver un moyen de s'inscrire à l'event, encore !
  <li> En revanche, j'ai créer la fonction qui n'affiche que les évenements enregistrés.. reste plus qu'a faire le lien
  <li> Déconnectez vous avec login / logout
  <li> Du love <3
</ul>

<iframe width="640" height="360" src="https://www.youtube.com/embed/S2lgnitdPdc?autoplay=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>